# Generated by Django 5.1.1 on 2024-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
