# Generated by Django 5.1.1 on 2024-09-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0002_suggestion_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='discription2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='gameImage',
            field=models.ImageField(blank=True, upload_to='media/homescreen'),
        ),
    ]
