# Generated by Django 5.0.7 on 2024-09-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0003_suggestion_discription2_suggestion_gameimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='gameImage',
            field=models.ImageField(blank=True, upload_to='homescreen'),
        ),
    ]
