# Generated by Django 5.0.7 on 2024-09-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0006_remove_gamegenre_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegenre',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
